spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/parallel_cart}
    username: ${SPRING_DATASOURCE_USERNAME:parallel_cart}
    password: ${SPRING_DATASOURCE_PASSWORD:parallel_cart}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.parallelcart.infra.messaging.events"
        spring.json.value.default.type: "com.parallelcart.infra.messaging.events.OrderCreatedEvent"

app:
  cache:
    product:
      ttl-seconds: 60
  kafka:
    topics:
      order-created: order.created
      order-created-dlq: order.created.dlq
    retry:
      max-attempts: 3
      interval-ms: 1000
  outbox:
    max-publish-attempts: 5
    publisher:
      fixed-delay-ms: 2000
